/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package biblioteca;

import java.util.*;

/**
 *
 * @author tomas
 */
public class BibliotecaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUItest
     */
    public BibliotecaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masculinoFeminino = new javax.swing.ButtonGroup();
        autenticacao = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameEmailLoginLabel = new javax.swing.JLabel();
        passwordLoginLabel = new javax.swing.JLabel();
        autenticacaoLabel = new javax.swing.JLabel();
        iniciarSessao = new javax.swing.JButton();
        novaContaLabel = new javax.swing.JLabel();
        nomeCompletoField = new javax.swing.JTextField();
        eMailField = new javax.swing.JTextField();
        reinEmailField = new javax.swing.JTextField();
        diaNascimento = new javax.swing.JComboBox();
        mesNascimento = new javax.swing.JComboBox();
        anoNascimento = new javax.swing.JComboBox();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        nomeCompletoLabel = new javax.swing.JLabel();
        eMailLabel = new javax.swing.JLabel();
        reinEmailLabel = new javax.swing.JLabel();
        passwordRegistoLabel = new javax.swing.JLabel();
        reinPasswordLabel = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        sobreLabel = new javax.swing.JLabel();
        contactosLabel = new javax.swing.JLabel();
        registar = new javax.swing.JButton();
        mainImage = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        passwordRegistoField = new javax.swing.JPasswordField();
        reinPasswordRegistoField = new javax.swing.JPasswordField();
        avisoemailrepetido = new javax.swing.JLabel();
        completarRegisto = new javax.swing.JPanel();
        moradaField = new javax.swing.JTextField();
        anteriorCompletarRegisto = new javax.swing.JButton();
        completarRegistoLabel = new javax.swing.JLabel();
        moradaLabel = new javax.swing.JLabel();
        codigoPostalLabel = new javax.swing.JLabel();
        codigoPostalField1 = new javax.swing.JTextField();
        codigoPostalField2 = new javax.swing.JTextField();
        hifenLabel = new javax.swing.JLabel();
        localidadeLabel = new javax.swing.JLabel();
        localidadeField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameDefField = new javax.swing.JTextField();
        seguinteCompletarRegisto = new javax.swing.JButton();
        erroRegisto = new javax.swing.JLabel();
        menuLeitor = new javax.swing.JPanel();
        terminarSessaoLeitor = new javax.swing.JButton();

        masculinoFeminino.add(masculino);
        masculinoFeminino.add(feminino);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName("bibliotecaFrame"); // NOI18N

        autenticacao.setBackground(new java.awt.Color(255, 255, 255));
        autenticacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        autenticacao.setToolTipText("");

        usernameField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField.setText("mail@tomasfrancisco.com");
        usernameField.setMinimumSize(new java.awt.Dimension(6, 20));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordField.setText("tomas");
        passwordField.setToolTipText("password");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        usernameEmailLoginLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        usernameEmailLoginLabel.setText("Username / E-mail");

        passwordLoginLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        passwordLoginLabel.setText("Password");

        autenticacaoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        autenticacaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        autenticacaoLabel.setText("Biblioteca");

        iniciarSessao.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        iniciarSessao.setText("Iniciar Sessão");
        iniciarSessao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciarSessao.setMaximumSize(new java.awt.Dimension(103, 24));
        iniciarSessao.setMinimumSize(new java.awt.Dimension(103, 24));
        iniciarSessao.setPreferredSize(new java.awt.Dimension(103, 24));
        iniciarSessao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iniciarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSessaoActionPerformed(evt);
            }
        });

        novaContaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        novaContaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        novaContaLabel.setText("Ainda não tem conta?");

        nomeCompletoField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        nomeCompletoField.setText("Tomás Luís Fonseca Francisco");
        nomeCompletoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompletoFieldActionPerformed(evt);
            }
        });

        eMailField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        eMailField.setText("mail@tomasfrancisco.com");
        eMailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailFieldActionPerformed(evt);
            }
        });

        reinEmailField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        reinEmailField.setText("mail@tomasfrancisco.com");
        reinEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinEmailFieldActionPerformed(evt);
            }
        });

        diaNascimento.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        diaNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaNascimento.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                diaNascimentoMouseWheelMoved(evt);
            }
        });
        diaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaNascimentoActionPerformed(evt);
            }
        });

        mesNascimento.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        mesNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoNascimento.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        anoNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013" }));

        masculino.setBackground(new java.awt.Color(255, 255, 255));
        masculino.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        feminino.setBackground(new java.awt.Color(255, 255, 255));
        feminino.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        feminino.setText("Feminino");

        nomeCompletoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        nomeCompletoLabel.setText("Nome Completo");

        eMailLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        eMailLabel.setText("E-mail");

        reinEmailLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        reinEmailLabel.setText("Reintroduza o E-mail");

        passwordRegistoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        passwordRegistoLabel.setText("Password");

        reinPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        reinPasswordLabel.setText("Reintroduza a Password");

        dataNascimentoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        dataNascimentoLabel.setText("Data de Nascimento");

        sobreLabel.setText("Sobre");

        contactosLabel.setText("Contactos");

        registar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        registar.setText("Registar");
        registar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarActionPerformed(evt);
            }
        });

        mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/AuthImage.png"))); // NOI18N

        generoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        generoLabel.setText("Género");

        passwordRegistoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordRegistoField.setText("tomas");
        passwordRegistoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegistoFieldActionPerformed(evt);
            }
        });

        reinPasswordRegistoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reinPasswordRegistoField.setText("tomas");

        javax.swing.GroupLayout autenticacaoLayout = new javax.swing.GroupLayout(autenticacao);
        autenticacao.setLayout(autenticacaoLayout);
        autenticacaoLayout.setHorizontalGroup(
            autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autenticacaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autenticacaoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eMailField)
                            .addComponent(reinEmailField)
                            .addComponent(nomeCompletoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeCompletoField)
                            .addGroup(autenticacaoLayout.createSequentialGroup()
                                .addComponent(novaContaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(166, 166, 166))
                            .addGroup(autenticacaoLayout.createSequentialGroup()
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(autenticacaoLayout.createSequentialGroup()
                                        .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dataNascimentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(autenticacaoLayout.createSequentialGroup()
                                        .addComponent(feminino)
                                        .addGap(10, 10, 10)
                                        .addComponent(masculino))
                                    .addComponent(generoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(registar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reinEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reinPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reinPasswordRegistoField)
                            .addComponent(passwordRegistoField)
                            .addGroup(autenticacaoLayout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(sobreLabel)
                                .addGap(18, 18, 18)
                                .addComponent(contactosLabel)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(autenticacaoLayout.createSequentialGroup()
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameEmailLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iniciarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(autenticacaoLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(avisoemailrepetido)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        autenticacaoLayout.setVerticalGroup(
            autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autenticacaoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autenticacaoLayout.createSequentialGroup()
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameEmailLoginLabel)
                            .addComponent(passwordLoginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iniciarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autenticacaoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(novaContaLabel)
                        .addGap(44, 44, 44)
                        .addComponent(nomeCompletoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCompletoField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eMailLabel)
                        .addGap(4, 4, 4)
                        .addComponent(eMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordRegistoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordRegistoField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinPasswordRegistoField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataNascimentoLabel)
                            .addComponent(generoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feminino)
                            .addComponent(masculino))
                        .addGap(18, 18, 18)
                        .addComponent(registar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(avisoemailrepetido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sobreLabel)
                            .addComponent(contactosLabel)))
                    .addComponent(mainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        completarRegisto.setBackground(new java.awt.Color(255, 255, 255));
        completarRegisto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        completarRegisto.setEnabled(false);
        completarRegisto.setPreferredSize(new java.awt.Dimension(1061, 749));

        moradaField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        moradaField.setText("Bairro da Reboleirada, Nº6");
        moradaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moradaFieldActionPerformed(evt);
            }
        });

        anteriorCompletarRegisto.setBackground(new java.awt.Color(255, 255, 255));
        anteriorCompletarRegisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/left_round-32.png"))); // NOI18N
        anteriorCompletarRegisto.setToolTipText("");
        anteriorCompletarRegisto.setBorder(null);
        anteriorCompletarRegisto.setBorderPainted(false);
        anteriorCompletarRegisto.setContentAreaFilled(false);
        anteriorCompletarRegisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorCompletarRegistoActionPerformed(evt);
            }
        });

        completarRegistoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        completarRegistoLabel.setText("Complete o seu registo");

        moradaLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        moradaLabel.setText("Morada, Nº Porta");

        codigoPostalLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        codigoPostalLabel.setText("Código postal");

        codigoPostalField1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        codigoPostalField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codigoPostalField1.setText("6215");
        codigoPostalField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalField1ActionPerformed(evt);
            }
        });

        codigoPostalField2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        codigoPostalField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codigoPostalField2.setText("318");
        codigoPostalField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalField2ActionPerformed(evt);
            }
        });

        hifenLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        hifenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hifenLabel.setText("-");

        localidadeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        localidadeLabel.setText("Localidade");

        localidadeField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        localidadeField.setText("Paul, Covilhã");
        localidadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadeFieldActionPerformed(evt);
            }
        });

        telefoneLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        telefoneLabel.setText("Telefone");

        telefoneField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        telefoneField.setText("968158474");
        telefoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFieldActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        usernameLabel.setText("Defina um username para iniciar sessão");

        usernameDefField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        usernameDefField.setText("tfrancisco");
        usernameDefField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameDefFieldActionPerformed(evt);
            }
        });

        seguinteCompletarRegisto.setBackground(new java.awt.Color(255, 255, 255));
        seguinteCompletarRegisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/right_round-32.png"))); // NOI18N
        seguinteCompletarRegisto.setToolTipText("");
        seguinteCompletarRegisto.setBorder(null);
        seguinteCompletarRegisto.setBorderPainted(false);
        seguinteCompletarRegisto.setContentAreaFilled(false);
        seguinteCompletarRegisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguinteCompletarRegistoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout completarRegistoLayout = new javax.swing.GroupLayout(completarRegisto);
        completarRegisto.setLayout(completarRegistoLayout);
        completarRegistoLayout.setHorizontalGroup(
            completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completarRegistoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anteriorCompletarRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seguinteCompletarRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(completarRegistoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(completarRegistoLayout.createSequentialGroup()
                        .addComponent(completarRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(completarRegistoLayout.createSequentialGroup()
                        .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(completarRegistoLayout.createSequentialGroup()
                                .addComponent(codigoPostalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hifenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoPostalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(localidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completarRegistoLayout.createSequentialGroup()
                        .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moradaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moradaField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, completarRegistoLayout.createSequentialGroup()
                                .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(codigoPostalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(localidadeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 188, Short.MAX_VALUE)))
                        .addGap(578, 578, 578))
                    .addGroup(completarRegistoLayout.createSequentialGroup()
                        .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameDefField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(erroRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        completarRegistoLayout.setVerticalGroup(
            completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completarRegistoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anteriorCompletarRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seguinteCompletarRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(completarRegistoLabel)
                .addGap(75, 75, 75)
                .addComponent(moradaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moradaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoPostalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completarRegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPostalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoPostalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hifenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localidadeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameDefField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(erroRegisto)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        menuLeitor.setBackground(new java.awt.Color(255, 255, 255));
        menuLeitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuLeitor.setPreferredSize(new java.awt.Dimension(1061, 749));

        terminarSessaoLeitor.setBackground(new java.awt.Color(255, 255, 255));
        terminarSessaoLeitor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        terminarSessaoLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/logout-32.png"))); // NOI18N
        terminarSessaoLeitor.setText("Terminar Sessão");
        terminarSessaoLeitor.setToolTipText("");
        terminarSessaoLeitor.setBorder(null);
        terminarSessaoLeitor.setBorderPainted(false);
        terminarSessaoLeitor.setContentAreaFilled(false);
        terminarSessaoLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarSessaoLeitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLeitorLayout = new javax.swing.GroupLayout(menuLeitor);
        menuLeitor.setLayout(menuLeitorLayout);
        menuLeitorLayout.setHorizontalGroup(
            menuLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLeitorLayout.createSequentialGroup()
                .addContainerGap(874, Short.MAX_VALUE)
                .addComponent(terminarSessaoLeitor)
                .addContainerGap())
        );
        menuLeitorLayout.setVerticalGroup(
            menuLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(terminarSessaoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autenticacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(completarRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autenticacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(completarRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoActionPerformed

    private void diaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaNascimentoActionPerformed

    private void reinEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinEmailFieldActionPerformed

    private void eMailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailFieldActionPerformed

    private void iniciarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSessaoActionPerformed

        String usernameString = this.usernameField.getText();
        String passwordString = new String(this.passwordField.getPassword());

        if(Autenticacao.login(Gestor.getUtilizadores(), usernameString, passwordString))
        {
            
            if(Gestor.getUtilizador(usernameString).getUsername().equals("NULL"))
            {
                this.setContentPane(this.completarRegisto);
            }
            else
            {
                this.setContentPane(this.menuLeitor);
            }
            avisoemailrepetido.setText("");
        }
        else
        {
            //TODO
        }
    }//GEN-LAST:event_iniciarSessaoActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void diaNascimentoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_diaNascimentoMouseWheelMoved
        // TODO add your handling code here:
        System.out.println("CONSOME");
        evt.consume();
        this.diaNascimento.showPopup();
    }//GEN-LAST:event_diaNascimentoMouseWheelMoved

    private void registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarActionPerformed
        // TODO add your handling code here:
        String nomeCompleto = this.nomeCompletoField.getText();
        String eMail = this.eMailField.getText();
        String password = new String(this.passwordRegistoField.getPassword());
        String dataNascimento = this.diaNascimento.getSelectedItem().toString() + "/" + this.mesNascimento.getSelectedItem().toString() + "/" + this.anoNascimento.getSelectedItem().toString();
        String genero;
        if(this.feminino.isSelected())
        {
            genero = "Feminino";
        }
        else if(this.masculino.isSelected())
        {
            genero = "Masculino";
        }
        else
        {
            genero = "ERRO";
        }
        if(biblioteca.Gestor.verificaEmail(eMail)==false)
        {
            avisoemailrepetido.setText("O Email Inserido já se Encontra Resgitado!");
            System.out.println("Registo não foi efectuado com sucesso!");
        }
        else
        {
            Utilizador novoUtilizador = new Leitor(nomeCompleto, genero, "NULL", "NULL", "NULL", "NULL", eMail, dataNascimento, "NULL", password, ALUNO);
            Gestor.setUtilizador(novoUtilizador);
            avisoemailrepetido.setText("Registo efectuado com sucesso!");        
            System.out.println("Registo efectuado com sucesso!");        
        }
    }//GEN-LAST:event_registarActionPerformed
    /**
     * Esta metodo tem como funcao a verificacao da existencia do email nos utilizadores ja existentes
     * @param email
     * @return 
     */
       
    private void anteriorCompletarRegistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorCompletarRegistoActionPerformed
        // TODO add your handling code here:
        this.setContentPane(this.autenticacao);
    }//GEN-LAST:event_anteriorCompletarRegistoActionPerformed

    private void moradaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moradaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moradaFieldActionPerformed

    private void nomeCompletoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompletoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletoFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordRegistoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegistoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegistoFieldActionPerformed

    private void codigoPostalField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalField1ActionPerformed

    private void codigoPostalField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalField2ActionPerformed

    private void localidadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadeFieldActionPerformed

    private void telefoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFieldActionPerformed

    private void usernameDefFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameDefFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameDefFieldActionPerformed

    private void seguinteCompletarRegistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguinteCompletarRegistoActionPerformed
        // TODO add your handling code here:
        String eMail = this.usernameField.getText();
        String morada = this.moradaField.getText();
        String codigo_postal = this.codigoPostalField1.getText() + "-" + this.codigoPostalField2.getText();
        String localidade = this.localidadeField.getText();
        String telefone = this.telefoneField.getText();
        String usernameDef = this.usernameDefField.getText();
        if(biblioteca.Gestor.verificaUser(usernameDef)==true)
        {
            if(biblioteca.Gestor.verificaTelefone(telefone)==true)
            {
                Utilizador user = Gestor.getUtilizador(eMail);
                user.setMorada(morada);
                user.setCodigo_postal(codigo_postal);
                user.setLocalidade(localidade);
                user.setTelefone(telefone);
                user.setUsername(usernameDef);            
                this.setContentPane(this.menuLeitor);
                erroRegisto.setText("");
            }
            else
                erroRegisto.setText("O Telefone já se encontra ocupado");
        }
        else
            erroRegisto.setText("O Nome de Utilizador já se encontra ocupado");
    }//GEN-LAST:event_seguinteCompletarRegistoActionPerformed
     
    private void terminarSessaoLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarSessaoLeitorActionPerformed
        // TODO add your handling code here:
        this.usernameField.setText("");
        this.passwordField.setText("");
        this.setContentPane(this.autenticacao);
    }//GEN-LAST:event_terminarSessaoLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Administrador
        Gestor.setUtilizador(new Administrador("admin", "NULL", "NULL", "NULL", "NULL", "NULL", "admin@admin.com", "NULL", "admin", "admin", ADMIN));
        // Fim do Administrador
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {            
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());               
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BibliotecaGUI().setVisible(true);
            }
        });
    }
    
    // Constants declaration
    protected static final int ALUNO = 1;
    protected static final int PROF = 2;
    protected static final int ADMIN = 3;
    protected static final int ERRO = -1;
    // End of constants declaration
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anoNascimento;
    private javax.swing.JButton anteriorCompletarRegisto;
    private javax.swing.JPanel autenticacao;
    private javax.swing.JLabel autenticacaoLabel;
    private javax.swing.JLabel avisoemailrepetido;
    private javax.swing.JTextField codigoPostalField1;
    private javax.swing.JTextField codigoPostalField2;
    private javax.swing.JLabel codigoPostalLabel;
    private javax.swing.JPanel completarRegisto;
    private javax.swing.JLabel completarRegistoLabel;
    private javax.swing.JLabel contactosLabel;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JComboBox diaNascimento;
    private javax.swing.JTextField eMailField;
    private javax.swing.JLabel eMailLabel;
    private javax.swing.JLabel erroRegisto;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel hifenLabel;
    private javax.swing.JButton iniciarSessao;
    private javax.swing.JTextField localidadeField;
    private javax.swing.JLabel localidadeLabel;
    private javax.swing.JLabel mainImage;
    private javax.swing.JRadioButton masculino;
    private javax.swing.ButtonGroup masculinoFeminino;
    private javax.swing.JPanel menuLeitor;
    private javax.swing.JComboBox mesNascimento;
    private javax.swing.JTextField moradaField;
    private javax.swing.JLabel moradaLabel;
    private javax.swing.JTextField nomeCompletoField;
    private javax.swing.JLabel nomeCompletoLabel;
    private javax.swing.JLabel novaContaLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JPasswordField passwordRegistoField;
    private javax.swing.JLabel passwordRegistoLabel;
    private javax.swing.JButton registar;
    private javax.swing.JTextField reinEmailField;
    private javax.swing.JLabel reinEmailLabel;
    private javax.swing.JLabel reinPasswordLabel;
    private javax.swing.JPasswordField reinPasswordRegistoField;
    private javax.swing.JButton seguinteCompletarRegisto;
    private javax.swing.JLabel sobreLabel;
    private javax.swing.JTextField telefoneField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JButton terminarSessaoLeitor;
    private javax.swing.JTextField usernameDefField;
    private javax.swing.JLabel usernameEmailLoginLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}