/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package biblioteca;

/**
 *
 * @author tomas
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form BoasVindas
     */
    public Biblioteca() {
        initComponents();
        menuBiblioteca.setVisible(true);
        menuCompletarDados.setVisible(false);
        menuLeitor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoButtonGroup = new javax.swing.ButtonGroup();
        bibliotecaGUI = new javax.swing.JDesktopPane();
        menuBiblioteca = new javax.swing.JPanel();
        cabecalhoBibliotecaPanel = new javax.swing.JPanel();
        bibliotecaLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        iniciarSessaoButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        palavraPasseLabel = new javax.swing.JLabel();
        palavraPasseField = new javax.swing.JPasswordField();
        avisosInicioSessaoLabel = new javax.swing.JLabel();
        imagemBibliotecaPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        novoRegistoBibliotecaPanel = new javax.swing.JPanel();
        novaContaLabel = new javax.swing.JLabel();
        nomeCompletoLabel = new javax.swing.JLabel();
        nomeCompletoField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        reEmailLabel = new javax.swing.JLabel();
        reEmailField = new javax.swing.JTextField();
        palavraPasseRegistoLabel = new javax.swing.JLabel();
        rePalavraPasseRegistoLabel = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        diaComboBox = new javax.swing.JComboBox();
        mesComboBox = new javax.swing.JComboBox();
        anoComboBox = new javax.swing.JComboBox();
        generoLabel = new javax.swing.JLabel();
        femininoRadioButton = new javax.swing.JRadioButton();
        masculinoRadioButton = new javax.swing.JRadioButton();
        registarButton = new javax.swing.JButton();
        avisosRegistoLabel = new javax.swing.JLabel();
        palavraPasseRegistoField = new javax.swing.JPasswordField();
        rePalavraPasseRegistoField = new javax.swing.JPasswordField();
        menuCompletarDados = new javax.swing.JPanel();
        cabecalhoCompletarDadosPanel = new javax.swing.JPanel();
        quaseProntoLabel = new javax.swing.JLabel();
        avancarButton = new javax.swing.JButton();
        retornarButton = new javax.swing.JButton();
        completarRegistoPanel = new javax.swing.JPanel();
        completeLabel = new javax.swing.JLabel();
        moradaLabel = new javax.swing.JLabel();
        moradaField = new javax.swing.JTextField();
        codigoPostalLabel = new javax.swing.JLabel();
        codigoPostalField1 = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        codigoPostalField2 = new javax.swing.JTextField();
        localidadeField = new javax.swing.JTextField();
        localidadeLabel = new javax.swing.JLabel();
        telefoneField = new javax.swing.JTextField();
        definirUsernameLabel = new javax.swing.JLabel();
        usernameAvisoLabel = new javax.swing.JLabel();
        definirUsernameField = new javax.swing.JTextField();
        hifenLabel = new javax.swing.JLabel();
        avisoCompletarDadosLabel = new javax.swing.JLabel();
        imagemCompletarDadosPanel = new javax.swing.JPanel();
        imagemCompletarDadosLabel = new javax.swing.JLabel();
        menuLeitor = new javax.swing.JPanel();
        cabecalhoMenuLeitorPanel = new javax.swing.JPanel();
        bemVindoLabel = new javax.swing.JLabel();
        boasVindasNomeCompletoLabel = new javax.swing.JLabel();
        retornarMenuLeitorButton = new javax.swing.JButton();
        avancarMenuLeitorButton = new javax.swing.JButton();
        terminarSessaoMenuLeitorButton = new javax.swing.JButton();
        requisicao = new javax.swing.JPanel();

        generoButtonGroup.add(femininoRadioButton);
        generoButtonGroup.add(masculinoRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setResizable(false);

        bibliotecaGUI.setMaximumSize(new java.awt.Dimension(800, 600));
        bibliotecaGUI.setMinimumSize(new java.awt.Dimension(800, 600));

        menuBiblioteca.setBackground(new java.awt.Color(255, 255, 255));
        menuBiblioteca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuBiblioteca.setMaximumSize(new java.awt.Dimension(800, 600));
        menuBiblioteca.setMinimumSize(new java.awt.Dimension(800, 600));
        menuBiblioteca.setPreferredSize(new java.awt.Dimension(800, 600));

        cabecalhoBibliotecaPanel.setBackground(new java.awt.Color(255, 255, 255));
        cabecalhoBibliotecaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bibliotecaLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bibliotecaLabel.setText("Biblioteca");

        usernameField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        usernameField.setText("mail@tomasfrancisco.com");

        iniciarSessaoButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        iniciarSessaoButton.setText("Iniciar Sessão");
        iniciarSessaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSessaoButtonActionPerformed(evt);
            }
        });

        usernameLabel.setText("E-mail ou username:");

        palavraPasseLabel.setText("Palavra-passe:");

        palavraPasseField.setText("tomas");

        avisosInicioSessaoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        avisosInicioSessaoLabel.setForeground(new java.awt.Color(255, 0, 0));
        avisosInicioSessaoLabel.setText("Avisos");

        javax.swing.GroupLayout cabecalhoBibliotecaPanelLayout = new javax.swing.GroupLayout(cabecalhoBibliotecaPanel);
        cabecalhoBibliotecaPanel.setLayout(cabecalhoBibliotecaPanelLayout);
        cabecalhoBibliotecaPanelLayout.setHorizontalGroup(
            cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoBibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bibliotecaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(6, 6, 6)
                .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palavraPasseField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palavraPasseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoBibliotecaPanelLayout.createSequentialGroup()
                        .addComponent(iniciarSessaoButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(avisosInicioSessaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cabecalhoBibliotecaPanelLayout.setVerticalGroup(
            cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoBibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bibliotecaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoBibliotecaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palavraPasseLabel)
                            .addComponent(usernameLabel)
                            .addComponent(avisosInicioSessaoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cabecalhoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(palavraPasseField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iniciarSessaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        imagemBibliotecaPanel.setBackground(new java.awt.Color(255, 255, 255));
        imagemBibliotecaPanel.setPreferredSize(new java.awt.Dimension(380, 462));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/authImage.jpg"))); // NOI18N

        javax.swing.GroupLayout imagemBibliotecaPanelLayout = new javax.swing.GroupLayout(imagemBibliotecaPanel);
        imagemBibliotecaPanel.setLayout(imagemBibliotecaPanelLayout);
        imagemBibliotecaPanelLayout.setHorizontalGroup(
            imagemBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemBibliotecaPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        imagemBibliotecaPanelLayout.setVerticalGroup(
            imagemBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemBibliotecaPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        novoRegistoBibliotecaPanel.setBackground(new java.awt.Color(255, 255, 255));
        novoRegistoBibliotecaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        novaContaLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        novaContaLabel.setText("Ainda não tem conta?");

        nomeCompletoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        nomeCompletoLabel.setText("Nome Completo:");

        nomeCompletoField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        nomeCompletoField.setText("Tomás Luís Fonseca Francisco");

        emailLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        emailLabel.setText("E-mail:");

        emailField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        emailField.setText("mail@tomasfrancisco.com");

        reEmailLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        reEmailLabel.setText("Reintroduza o E-mail:");

        reEmailField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        reEmailField.setText("mail@tomasfrancisco.com");

        palavraPasseRegistoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        palavraPasseRegistoLabel.setText("Palavra-passe:");

        rePalavraPasseRegistoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        rePalavraPasseRegistoLabel.setText("Reintroduza a Palavra-passe:");

        dataNascimentoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        dataNascimentoLabel.setText("Data de Nascimento:");

        diaComboBox.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        diaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesComboBox.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        mesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoComboBox.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        anoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));

        generoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        generoLabel.setText("Género:");

        femininoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        femininoRadioButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        femininoRadioButton.setText("Feminino");

        masculinoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        masculinoRadioButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        masculinoRadioButton.setText("Masculino");

        registarButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        registarButton.setText("Registar");
        registarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarButtonActionPerformed(evt);
            }
        });

        avisosRegistoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        avisosRegistoLabel.setForeground(new java.awt.Color(255, 0, 0));
        avisosRegistoLabel.setText("Avisos");

        palavraPasseRegistoField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        palavraPasseRegistoField.setText("tomas");

        rePalavraPasseRegistoField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rePalavraPasseRegistoField.setText("jPasswordField2");

        javax.swing.GroupLayout novoRegistoBibliotecaPanelLayout = new javax.swing.GroupLayout(novoRegistoBibliotecaPanel);
        novoRegistoBibliotecaPanel.setLayout(novoRegistoBibliotecaPanelLayout);
        novoRegistoBibliotecaPanelLayout.setHorizontalGroup(
            novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCompletoField)
                    .addComponent(nomeCompletoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailField)
                    .addComponent(novaContaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reEmailField)
                    .addComponent(registarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avisosRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(palavraPasseRegistoField)
                    .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                        .addGroup(novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                                .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataNascimentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                                .addComponent(femininoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masculinoRadioButton))
                            .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(generoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rePalavraPasseRegistoField)
                    .addComponent(palavraPasseRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rePalavraPasseRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        novoRegistoBibliotecaPanelLayout.setVerticalGroup(
            novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novoRegistoBibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novaContaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(nomeCompletoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCompletoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palavraPasseRegistoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palavraPasseRegistoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rePalavraPasseRegistoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rePalavraPasseRegistoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoLabel)
                    .addComponent(generoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(novoRegistoBibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femininoRadioButton)
                    .addComponent(masculinoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisosRegistoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuBibliotecaLayout = new javax.swing.GroupLayout(menuBiblioteca);
        menuBiblioteca.setLayout(menuBibliotecaLayout);
        menuBibliotecaLayout.setHorizontalGroup(
            menuBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBibliotecaLayout.createSequentialGroup()
                        .addComponent(imagemBibliotecaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(novoRegistoBibliotecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cabecalhoBibliotecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuBibliotecaLayout.setVerticalGroup(
            menuBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoBibliotecaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemBibliotecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novoRegistoBibliotecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuCompletarDados.setBackground(new java.awt.Color(255, 255, 255));
        menuCompletarDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuCompletarDados.setMaximumSize(new java.awt.Dimension(800, 600));
        menuCompletarDados.setMinimumSize(new java.awt.Dimension(800, 600));
        menuCompletarDados.setPreferredSize(new java.awt.Dimension(800, 600));

        cabecalhoCompletarDadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        cabecalhoCompletarDadosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cabecalhoCompletarDadosPanel.setPreferredSize(new java.awt.Dimension(777, 106));

        quaseProntoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        quaseProntoLabel.setText("Está quase tudo pronto...");

        avancarButton.setBackground(new java.awt.Color(255, 255, 255));
        avancarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/right_round-32.png"))); // NOI18N
        avancarButton.setBorder(null);
        avancarButton.setBorderPainted(false);
        avancarButton.setContentAreaFilled(false);
        avancarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarButtonActionPerformed(evt);
            }
        });

        retornarButton.setBackground(new java.awt.Color(255, 255, 255));
        retornarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left_round-32.png"))); // NOI18N
        retornarButton.setBorder(null);
        retornarButton.setBorderPainted(false);
        retornarButton.setContentAreaFilled(false);
        retornarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoCompletarDadosPanelLayout = new javax.swing.GroupLayout(cabecalhoCompletarDadosPanel);
        cabecalhoCompletarDadosPanel.setLayout(cabecalhoCompletarDadosPanelLayout);
        cabecalhoCompletarDadosPanelLayout.setHorizontalGroup(
            cabecalhoCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoCompletarDadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quaseProntoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cabecalhoCompletarDadosPanelLayout.createSequentialGroup()
                        .addComponent(retornarButton)
                        .addGap(18, 18, 18)
                        .addComponent(avancarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cabecalhoCompletarDadosPanelLayout.setVerticalGroup(
            cabecalhoCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoCompletarDadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quaseProntoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(cabecalhoCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(retornarButton)
                    .addComponent(avancarButton))
                .addContainerGap())
        );

        completarRegistoPanel.setBackground(new java.awt.Color(255, 255, 255));
        completarRegistoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        completarRegistoPanel.setPreferredSize(new java.awt.Dimension(371, 459));

        completeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        completeLabel.setText("Complete os seguintes campos:");

        moradaLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        moradaLabel.setText("Morada, Nº Porta:");

        moradaField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        moradaField.setText("Bairro da Reboleirada, Nº 6");

        codigoPostalLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        codigoPostalLabel.setText("Código postal:");

        codigoPostalField1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        codigoPostalField1.setText("6215");

        telefoneLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        telefoneLabel.setText("Telefone:");

        codigoPostalField2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        codigoPostalField2.setText("318");
        codigoPostalField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalField2ActionPerformed(evt);
            }
        });

        localidadeField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        localidadeField.setText("Paul, Covilhã");

        localidadeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        localidadeLabel.setText("Localidade:");

        telefoneField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        telefoneField.setText("968158474");
        telefoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFieldActionPerformed(evt);
            }
        });

        definirUsernameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        definirUsernameLabel.setText("Defina um username:");

        usernameAvisoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        usernameAvisoLabel.setText("Permite-lhe iniciar sessão");

        definirUsernameField.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        definirUsernameField.setText("tfrancisco");
        definirUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirUsernameFieldActionPerformed(evt);
            }
        });

        hifenLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        hifenLabel.setText("-");

        avisoCompletarDadosLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        avisoCompletarDadosLabel.setForeground(new java.awt.Color(255, 0, 0));
        avisoCompletarDadosLabel.setText("Avisos");

        javax.swing.GroupLayout completarRegistoPanelLayout = new javax.swing.GroupLayout(completarRegistoPanel);
        completarRegistoPanel.setLayout(completarRegistoPanelLayout);
        completarRegistoPanelLayout.setHorizontalGroup(
            completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completarRegistoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moradaField)
                    .addComponent(moradaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(completarRegistoPanelLayout.createSequentialGroup()
                        .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(completarRegistoPanelLayout.createSequentialGroup()
                                .addComponent(codigoPostalField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hifenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoPostalField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localidadeField)
                            .addComponent(localidadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(definirUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(usernameAvisoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(definirUsernameField)
                    .addGroup(completarRegistoPanelLayout.createSequentialGroup()
                        .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefoneField)
                            .addComponent(telefoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(avisoCompletarDadosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        completarRegistoPanelLayout.setVerticalGroup(
            completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completarRegistoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(completeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(moradaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moradaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPostalLabel)
                    .addComponent(localidadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completarRegistoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPostalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoPostalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hifenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneLabel)
                .addGap(1, 1, 1)
                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(definirUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameAvisoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(definirUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisoCompletarDadosLabel)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        imagemCompletarDadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        imagemCompletarDadosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imagemCompletarDadosPanel.setPreferredSize(new java.awt.Dimension(380, 462));

        imagemCompletarDadosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Personal information.png"))); // NOI18N

        javax.swing.GroupLayout imagemCompletarDadosPanelLayout = new javax.swing.GroupLayout(imagemCompletarDadosPanel);
        imagemCompletarDadosPanel.setLayout(imagemCompletarDadosPanelLayout);
        imagemCompletarDadosPanelLayout.setHorizontalGroup(
            imagemCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemCompletarDadosPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(imagemCompletarDadosLabel)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        imagemCompletarDadosPanelLayout.setVerticalGroup(
            imagemCompletarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemCompletarDadosPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(imagemCompletarDadosLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuCompletarDadosLayout = new javax.swing.GroupLayout(menuCompletarDados);
        menuCompletarDados.setLayout(menuCompletarDadosLayout);
        menuCompletarDadosLayout.setHorizontalGroup(
            menuCompletarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCompletarDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuCompletarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecalhoCompletarDadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(menuCompletarDadosLayout.createSequentialGroup()
                        .addComponent(completarRegistoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(imagemCompletarDadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuCompletarDadosLayout.setVerticalGroup(
            menuCompletarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCompletarDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoCompletarDadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuCompletarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagemCompletarDadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(completarRegistoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuLeitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuLeitor.setMaximumSize(new java.awt.Dimension(800, 600));
        menuLeitor.setMinimumSize(new java.awt.Dimension(800, 600));
        menuLeitor.setPreferredSize(new java.awt.Dimension(800, 600));

        cabecalhoMenuLeitorPanel.setBackground(new java.awt.Color(255, 255, 255));
        cabecalhoMenuLeitorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cabecalhoMenuLeitorPanel.setPreferredSize(new java.awt.Dimension(777, 106));

        bemVindoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        bemVindoLabel.setText("Bem vindo");

        boasVindasNomeCompletoLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        boasVindasNomeCompletoLabel.setText("Nome Completo!");

        retornarMenuLeitorButton.setBackground(new java.awt.Color(255, 255, 255));
        retornarMenuLeitorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left_round-32.png"))); // NOI18N
        retornarMenuLeitorButton.setBorder(null);
        retornarMenuLeitorButton.setBorderPainted(false);
        retornarMenuLeitorButton.setContentAreaFilled(false);
        retornarMenuLeitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarMenuLeitorButtonActionPerformed(evt);
            }
        });

        avancarMenuLeitorButton.setBackground(new java.awt.Color(255, 255, 255));
        avancarMenuLeitorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/right_round-32.png"))); // NOI18N
        avancarMenuLeitorButton.setBorder(null);
        avancarMenuLeitorButton.setBorderPainted(false);
        avancarMenuLeitorButton.setContentAreaFilled(false);
        avancarMenuLeitorButton.setEnabled(false);
        avancarMenuLeitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarMenuLeitorButtonActionPerformed(evt);
            }
        });

        terminarSessaoMenuLeitorButton.setBackground(new java.awt.Color(255, 255, 255));
        terminarSessaoMenuLeitorButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        terminarSessaoMenuLeitorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit-32.png"))); // NOI18N
        terminarSessaoMenuLeitorButton.setText("Terminar Sessão");
        terminarSessaoMenuLeitorButton.setBorder(null);
        terminarSessaoMenuLeitorButton.setBorderPainted(false);
        terminarSessaoMenuLeitorButton.setContentAreaFilled(false);
        terminarSessaoMenuLeitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarSessaoMenuLeitorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoMenuLeitorPanelLayout = new javax.swing.GroupLayout(cabecalhoMenuLeitorPanel);
        cabecalhoMenuLeitorPanel.setLayout(cabecalhoMenuLeitorPanelLayout);
        cabecalhoMenuLeitorPanelLayout.setHorizontalGroup(
            cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                        .addComponent(bemVindoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boasVindasNomeCompletoLabel)
                        .addGap(0, 423, Short.MAX_VALUE))
                    .addGroup(cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                        .addComponent(retornarMenuLeitorButton)
                        .addGap(18, 18, 18)
                        .addComponent(avancarMenuLeitorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terminarSessaoMenuLeitorButton)))
                .addContainerGap())
        );
        cabecalhoMenuLeitorPanelLayout.setVerticalGroup(
            cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terminarSessaoMenuLeitorButton))
                    .addGroup(cabecalhoMenuLeitorPanelLayout.createSequentialGroup()
                        .addGroup(cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bemVindoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boasVindasNomeCompletoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(cabecalhoMenuLeitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(retornarMenuLeitorButton)
                            .addComponent(avancarMenuLeitorButton))))
                .addContainerGap())
        );

        javax.swing.GroupLayout menuLeitorLayout = new javax.swing.GroupLayout(menuLeitor);
        menuLeitor.setLayout(menuLeitorLayout);
        menuLeitorLayout.setHorizontalGroup(
            menuLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoMenuLeitorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuLeitorLayout.setVerticalGroup(
            menuLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoMenuLeitorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        requisicao.setMaximumSize(new java.awt.Dimension(800, 600));
        requisicao.setMinimumSize(new java.awt.Dimension(800, 600));
        requisicao.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout requisicaoLayout = new javax.swing.GroupLayout(requisicao);
        requisicao.setLayout(requisicaoLayout);
        requisicaoLayout.setHorizontalGroup(
            requisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        requisicaoLayout.setVerticalGroup(
            requisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bibliotecaGUILayout = new javax.swing.GroupLayout(bibliotecaGUI);
        bibliotecaGUI.setLayout(bibliotecaGUILayout);
        bibliotecaGUILayout.setHorizontalGroup(
            bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuCompletarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(requisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bibliotecaGUILayout.setVerticalGroup(
            bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuCompletarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addComponent(menuLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(bibliotecaGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bibliotecaGUILayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(requisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bibliotecaGUI.setLayer(menuBiblioteca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bibliotecaGUI.setLayer(menuCompletarDados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bibliotecaGUI.setLayer(menuLeitor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bibliotecaGUI.setLayer(requisicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bibliotecaGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bibliotecaGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFieldActionPerformed

    private void definirUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_definirUsernameFieldActionPerformed

    private void codigoPostalField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalField2ActionPerformed

    private void retornarMenuLeitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarMenuLeitorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarMenuLeitorButtonActionPerformed

    private void avancarMenuLeitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarMenuLeitorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avancarMenuLeitorButtonActionPerformed

    private void avancarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarButtonActionPerformed
        String morada = moradaField.getText();
        String codigoPostar = codigoPostalField1.getText() + "-" + codigoPostalField2.getText();
        String localidade = localidadeField.getText();
        String telefone = telefoneField.getText();
        String username = definirUsernameField.getText();
        
        if(Gestor.verificaTelefone(telefone))
        {
            avisoCompletarDadosLabel.setText("Este telefone já se encontra registado");
            return;
        }
        else if(Gestor.verificaUser(username))
        {
            avisoCompletarDadosLabel.setText("Este username já se encontra registado");
            return;
        }
        
        Utilizador user = Gestor.getUtilizador(usernameField.getText());
        user.setMorada(morada);
        user.setCodigo_postal(codigoPostar);
        user.setLocalidade(localidade);
        user.setTelefone(telefone);
        user.setUsername(username);     
        
        menuCompletarDados.setVisible(false);
        menuLeitor.setVisible(true);
    }//GEN-LAST:event_avancarButtonActionPerformed

    private void retornarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarButtonActionPerformed
        menuCompletarDados.setVisible(false);
        menuBiblioteca.setVisible(true);
    }//GEN-LAST:event_retornarButtonActionPerformed

    private void terminarSessaoMenuLeitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarSessaoMenuLeitorButtonActionPerformed
        usernameField.setText("");
        palavraPasseField.setText("");
        menuLeitor.setVisible(false);
        menuBiblioteca.setVisible(true);
    }//GEN-LAST:event_terminarSessaoMenuLeitorButtonActionPerformed

    private void iniciarSessaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSessaoButtonActionPerformed
        String username = usernameField.getText();
        String palavraPasse = new String(palavraPasseField.getPassword());
        
        if(Gestor.login(username, palavraPasse))
        {
            menuBiblioteca.setVisible(false);
            if(Gestor.verificaPrimeiraVez(username))
            {
                menuCompletarDados.setVisible(true);
            }
            else
            {
                menuLeitor.setVisible(true);
            }
        }
        else
            avisosInicioSessaoLabel.setText("Dados inválidos");
    }//GEN-LAST:event_iniciarSessaoButtonActionPerformed

    private void registarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarButtonActionPerformed
        String nomeCompleto = nomeCompletoField.getText();
        String email = emailField.getText();
        String reEmail = reEmailField.getText();
        String palavraPasse = new String(palavraPasseRegistoField.getPassword());
        String rePalavraPasse = new String(rePalavraPasseRegistoField.getPassword());
        String dia = diaComboBox.getSelectedItem().toString();
        String mes = mesComboBox.getSelectedItem().toString();
        String ano = anoComboBox.getSelectedItem().toString();
        String dataNascimento = dia + " de " + mes + " de " + ano;
        String genero;
        
        if(this.femininoRadioButton.isSelected())
            genero = "Feminino";
        else if(masculinoRadioButton.isSelected())
            genero = "Masculino";
        else
        {
            avisosRegistoLabel.setText("Verifique o campo género");
            return;
        }
        
        if(biblioteca.Gestor.verificaEmail(email))
        {
            avisosRegistoLabel.setText("Este e-mail já se econtra registado");
            System.out.println("Registo não efectuado com sucesso");
            return;
        }
        
        Gestor.setUtilizador(new Leitor(nomeCompleto, genero, "NULL", "NULL", "NULL", "NULL", email, dataNascimento, "NULL", palavraPasse, Utilizador.ALUNO));
        System.out.println(Gestor.getUtilizadores().size());
        
        nomeCompletoField.setText("");
        emailField.setText("");
        reEmailField.setText("");
        palavraPasseRegistoField.setText("");
        rePalavraPasseRegistoField.setText("");
        diaComboBox.setSelectedIndex(0);
        mesComboBox.setSelectedIndex(0);
        anoComboBox.setSelectedIndex(0);
        femininoRadioButton.setSelected(false);
        masculinoRadioButton.setSelected(false);
        
        System.out.println("Registo efectuado com sucesso");        
    }//GEN-LAST:event_registarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anoComboBox;
    private javax.swing.JButton avancarButton;
    private javax.swing.JButton avancarMenuLeitorButton;
    private javax.swing.JLabel avisoCompletarDadosLabel;
    private javax.swing.JLabel avisosInicioSessaoLabel;
    private javax.swing.JLabel avisosRegistoLabel;
    private javax.swing.JLabel bemVindoLabel;
    private javax.swing.JDesktopPane bibliotecaGUI;
    private javax.swing.JLabel bibliotecaLabel;
    private javax.swing.JLabel boasVindasNomeCompletoLabel;
    private javax.swing.JPanel cabecalhoBibliotecaPanel;
    private javax.swing.JPanel cabecalhoCompletarDadosPanel;
    private javax.swing.JPanel cabecalhoMenuLeitorPanel;
    private javax.swing.JTextField codigoPostalField1;
    private javax.swing.JTextField codigoPostalField2;
    private javax.swing.JLabel codigoPostalLabel;
    private javax.swing.JPanel completarRegistoPanel;
    private javax.swing.JLabel completeLabel;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JTextField definirUsernameField;
    private javax.swing.JLabel definirUsernameLabel;
    private javax.swing.JComboBox diaComboBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton femininoRadioButton;
    private javax.swing.ButtonGroup generoButtonGroup;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel hifenLabel;
    private javax.swing.JPanel imagemBibliotecaPanel;
    private javax.swing.JLabel imagemCompletarDadosLabel;
    private javax.swing.JPanel imagemCompletarDadosPanel;
    private javax.swing.JButton iniciarSessaoButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField localidadeField;
    private javax.swing.JLabel localidadeLabel;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JPanel menuBiblioteca;
    private javax.swing.JPanel menuCompletarDados;
    private javax.swing.JPanel menuLeitor;
    private javax.swing.JComboBox mesComboBox;
    private javax.swing.JTextField moradaField;
    private javax.swing.JLabel moradaLabel;
    private javax.swing.JTextField nomeCompletoField;
    private javax.swing.JLabel nomeCompletoLabel;
    private javax.swing.JLabel novaContaLabel;
    private javax.swing.JPanel novoRegistoBibliotecaPanel;
    private javax.swing.JPasswordField palavraPasseField;
    private javax.swing.JLabel palavraPasseLabel;
    private javax.swing.JPasswordField palavraPasseRegistoField;
    private javax.swing.JLabel palavraPasseRegistoLabel;
    private javax.swing.JLabel quaseProntoLabel;
    private javax.swing.JTextField reEmailField;
    private javax.swing.JLabel reEmailLabel;
    private javax.swing.JPasswordField rePalavraPasseRegistoField;
    private javax.swing.JLabel rePalavraPasseRegistoLabel;
    private javax.swing.JButton registarButton;
    private javax.swing.JPanel requisicao;
    private javax.swing.JButton retornarButton;
    private javax.swing.JButton retornarMenuLeitorButton;
    private javax.swing.JTextField telefoneField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JButton terminarSessaoMenuLeitorButton;
    private javax.swing.JLabel usernameAvisoLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
