/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package biblioteca;

import java.util.*;

/**
 *
 * @author tomas
 */
public class BibliotecaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUItest
     */
    public BibliotecaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masculinoFeminino = new javax.swing.ButtonGroup();
        autenticacao = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameEmailLoginLabel = new javax.swing.JLabel();
        passwordLoginLabel = new javax.swing.JLabel();
        autenticacaoLabel = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nomeCompletoField = new javax.swing.JTextField();
        eMailField = new javax.swing.JTextField();
        reinEmailField = new javax.swing.JTextField();
        passwordFiel = new javax.swing.JTextField();
        reinPasswordField = new javax.swing.JTextField();
        diaNascimento = new javax.swing.JComboBox();
        mesNascimento = new javax.swing.JComboBox();
        anoNascimento = new javax.swing.JComboBox();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        nomeCompletoLabel = new javax.swing.JLabel();
        eMailLabel = new javax.swing.JLabel();
        reinEmailLabel = new javax.swing.JLabel();
        passwordRegistoLabel = new javax.swing.JLabel();
        reinPasswordLabel = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registar = new javax.swing.JButton();
        primeiroLogin = new javax.swing.JPanel();
        avisoPrimeiroLogin = new javax.swing.JLabel();
        avisoExtraPrimeiroLogin = new javax.swing.JLabel();
        moradaField = new javax.swing.JTextField();

        masculinoFeminino.add(masculino);
        masculinoFeminino.add(feminino);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");

        autenticacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        autenticacao.setToolTipText("");
        autenticacao.setPreferredSize(new java.awt.Dimension(910, 760));

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordField.setToolTipText("password");

        usernameEmailLoginLabel.setText("Username / E-mail");

        passwordLoginLabel.setText("Password");

        autenticacaoLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        autenticacaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autenticacaoLabel.setText("Biblioteca");

        login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Registo");

        eMailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailFieldActionPerformed(evt);
            }
        });

        reinEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinEmailFieldActionPerformed(evt);
            }
        });

        passwordFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFielActionPerformed(evt);
            }
        });

        reinPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinPasswordFieldActionPerformed(evt);
            }
        });

        diaNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaNascimento.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                diaNascimentoMouseWheelMoved(evt);
            }
        });
        diaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaNascimentoActionPerformed(evt);
            }
        });

        mesNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        anoNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013" }));

        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        feminino.setText("Feminino");

        nomeCompletoLabel.setText("Nome Completo");

        eMailLabel.setText("E-mail");

        reinEmailLabel.setText("Reintroduza o E-mail");

        passwordRegistoLabel.setText("Password");

        reinPasswordLabel.setText("Reintroduza a Password");

        dataNascimentoLabel.setText("Data de Nascimento");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/Biblioteca.jpg"))); // NOI18N

        jLabel1.setText("Sobre");

        jLabel4.setText("Contactos");

        registar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registar.setText("Registar");
        registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout autenticacaoLayout = new javax.swing.GroupLayout(autenticacao);
        autenticacao.setLayout(autenticacaoLayout);
        autenticacaoLayout.setHorizontalGroup(
            autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autenticacaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autenticacaoLayout.createSequentialGroup()
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNascimentoLabel)
                            .addComponent(reinPasswordLabel)
                            .addComponent(reinEmailLabel)
                            .addComponent(nomeCompletoLabel)
                            .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeCompletoField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reinEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eMailLabel)
                                    .addComponent(eMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordRegistoLabel)
                                    .addComponent(passwordFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(autenticacaoLayout.createSequentialGroup()
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameEmailLoginLabel)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLoginLabel)
                                    .addGroup(autenticacaoLayout.createSequentialGroup()
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(login))))
                            .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(registar, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, autenticacaoLayout.createSequentialGroup()
                                        .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(feminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(masculino))
                                    .addComponent(reinPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autenticacaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autenticacaoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))))
        );
        autenticacaoLayout.setVerticalGroup(
            autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticacaoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autenticacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(autenticacaoLayout.createSequentialGroup()
                            .addComponent(passwordLoginLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(autenticacaoLayout.createSequentialGroup()
                            .addComponent(usernameEmailLoginLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(autenticacaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomeCompletoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCompletoField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eMailLabel)
                        .addGap(4, 4, 4)
                        .addComponent(eMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinEmailLabel)
                        .addGap(4, 4, 4)
                        .addComponent(reinEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordRegistoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feminino)
                            .addComponent(masculino))
                        .addGap(18, 18, 18)
                        .addComponent(registar)
                        .addGap(163, 163, 163)
                        .addGroup(autenticacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        primeiroLogin.setPreferredSize(new java.awt.Dimension(910, 760));

        avisoPrimeiroLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        avisoPrimeiroLogin.setText("Antes de continuar complete os seguintes campos...");

        avisoExtraPrimeiroLogin.setText("Estes dados são obrigatórios para que possa efectuar qualquer requisição");

        javax.swing.GroupLayout primeiroLoginLayout = new javax.swing.GroupLayout(primeiroLogin);
        primeiroLogin.setLayout(primeiroLoginLayout);
        primeiroLoginLayout.setHorizontalGroup(
            primeiroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primeiroLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primeiroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisoPrimeiroLogin)
                    .addComponent(avisoExtraPrimeiroLogin)
                    .addComponent(moradaField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        primeiroLoginLayout.setVerticalGroup(
            primeiroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primeiroLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(avisoPrimeiroLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisoExtraPrimeiroLogin)
                .addGap(67, 67, 67)
                .addComponent(moradaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(557, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autenticacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(primeiroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autenticacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(primeiroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoActionPerformed

    private void diaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaNascimentoActionPerformed

    private void reinPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinPasswordFieldActionPerformed

    private void passwordFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFielActionPerformed

    private void reinEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinEmailFieldActionPerformed

    private void eMailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailFieldActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String usernameString, passwordString;

        usernameString = this.usernameField.getText();
        passwordString = this.passwordField.getText();

        ArrayList <Utilizador> users = Gestor.getUtilizadores();

        if(Autenticacao.login(users, usernameString, passwordString))
        {
            this.setContentPane(this.primeiroLogin);
        }
        else
        {
            
        }
    }//GEN-LAST:event_loginActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void diaNascimentoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_diaNascimentoMouseWheelMoved
        // TODO add your handling code here:
        System.out.println("CONSOME");
        evt.consume();
        this.diaNascimento.showPopup();
    }//GEN-LAST:event_diaNascimentoMouseWheelMoved

    private void registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarActionPerformed
        // TODO add your handling code here:
        String nomeCompleto = this.nomeCompletoField.getText();
        String eMail = this.eMailField.getText();
        String password = this.passwordFiel.getText();
        String dataNascimento = this.diaNascimento.getSelectedItem().toString() + "/" + this.mesNascimento.getSelectedItem().toString() + "/" + this.anoNascimento.getSelectedItem().toString();
        String genero;
        if(this.feminino.isSelected())
        {
            genero = "Feminino";
        }
        else if(this.masculino.isSelected())
        {
            genero = "Masculino";
        }
        else
        {
            genero = "ERRO";
        }

        Utilizador novoUtilizador = new Leitor(nomeCompleto, genero, "Não definida", "Não definido", eMail, dataNascimento, "Não definido", password, ALUNO);
        Gestor.setUtilizador(novoUtilizador);
        
        System.out.println("Registo efectuado com sucesso!");        
    }//GEN-LAST:event_registarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Administrador
        Gestor.setUtilizador(new Administrador("admin", "Não definido", "Não definida", "Não definido", "admin@admin.com", "Não definida", "admin", "admin", ADMIN));
        // Fim do Administrador
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {            
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());               
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BibliotecaGUI().setVisible(true);
            }
        });
    }
    
    // Constants declaration
    protected static final int ALUNO = 1;
    protected static final int PROF = 2;
    protected static final int ADMIN = 3;
    protected static final int ERRO = -1;
    // End of constants declaration
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anoNascimento;
    private javax.swing.JPanel autenticacao;
    private javax.swing.JLabel autenticacaoLabel;
    private javax.swing.JLabel avisoExtraPrimeiroLogin;
    private javax.swing.JLabel avisoPrimeiroLogin;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JComboBox diaNascimento;
    private javax.swing.JTextField eMailField;
    private javax.swing.JLabel eMailLabel;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JRadioButton masculino;
    private javax.swing.ButtonGroup masculinoFeminino;
    private javax.swing.JComboBox mesNascimento;
    private javax.swing.JTextField moradaField;
    private javax.swing.JTextField nomeCompletoField;
    private javax.swing.JLabel nomeCompletoLabel;
    private javax.swing.JTextField passwordFiel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JLabel passwordRegistoLabel;
    private javax.swing.JPanel primeiroLogin;
    private javax.swing.JButton registar;
    private javax.swing.JTextField reinEmailField;
    private javax.swing.JLabel reinEmailLabel;
    private javax.swing.JTextField reinPasswordField;
    private javax.swing.JLabel reinPasswordLabel;
    private javax.swing.JLabel usernameEmailLoginLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
